const String FETCHSITEINFORMATION = r'''
query ($domain: String!) {
  site(domain: $domain) {
    address
    androidApp
    affiliate {
      commission
      id
      serial
      title
    }
    affiliateCommission
    affiliateJoinCommission
    affiliateJoinFee
    affiliateJoinType
    affiliateType
    bpayMerchantId
    completedStep
    coverImage
    createdAt
    currency
    desktopLogo
    desktopTheme
    domain
    email
    favicon
    foot
    fraudTransactionLimit
    fraudWindowTime
    guide
    head
    hostname
    id
    industry
    isActive
    isFraudCheck
    isGuest
    isGuide
    isOtp
    isPaid
    isPublic
    isWhiteLabel
    itemLimit
    lastEvent
    lastPayment
    latitude
    locale
    longitude
    meta
    metaDescription
    metaTitle
    navigation
    notice
    parent {
      id
      isActive
      isFixed
      parentId
      percentage
      title
      userId
    }
    parents
    percentage
    phone
    phoneLogo
    queryType
    sendSmsPerEvent
    sendSmsPerOrder
    siteInfo
    siteType
    social
    street
    subscription
    subscriptionFee
    theme
    threshold
    title
    tools
    version
    whiteLabel
    whiteLabelUrl
    withdraw
  }
}
 ''';
